Fix Welcome Bot Support Link
MicrosoftDocs/feedback pull request #3814
Opened 2022-06-14 06:24 UTC by aisgbnok

### Description

- Closes #3813 

As described in #3813 the support link is wrong. I made a few other small changes, such as making the support link a markdown link with text. Here is what it will look like.

![Fixed Welcome Bot Support Link](https://user-images.githubusercontent.com/10838153/173507638-c8312634-185c-426c-ba5d-70a05fcb846d.png)

2022-06-17 05:13 UTC, Rick-Anderson approved these changes

2022-06-22 22:53 UTC, Rick-Anderson requested changes

2022-06-22 22:53 UTC, Rick-Anderson commented on .github/config.yml
> +  Thank you for opening an issue! One of our team members will get back to you shortly with additional information.
```suggestion
Thank you for opening an issue! One of our team members will get back to you shortly with additional information.
```

2022-06-23 01:02 UTC, aisgbnok commented
Hey @Rick-Anderson, thanks for the suggestions.

I'm not going to commit them at the moment, because I believe the indentation is required. At least I just tested it on my fork and it wouldn't service a welcome comment without the indent. I also have two empty lines because a single empty line in markdown doesn't render as an empty line.

I added the paragraph separation between the two lines (as seen in the PR description screenshot) because I thought it looked better. If you think there should be no separation then I'll commit that suggestion with you as co-author. Thanks!

2022-06-23 01:04 UTC, aisgbnok commented on .github/config.yml
> +  Thank you for opening an issue! One of our team members will get back to you shortly with additional information.
I believe this is required.

2022-06-23 01:54 UTC, Rick-Anderson commented
> I also have two empty lines because a single empty line in markdown doesn't render as an empty line.

You need two spaces in the empty line I think.

2022-06-23 01:55 UTC, Rick-Anderson approved these changes

2022-06-26 13:00 UTC, aisgbnok commented
@Rick-Anderson, sorry for my slow response. Your right, using two spaces on a single empty line does work! I think I prefer this to my two empty lines as well. 👍

2022-11-03 16:43 UTC, briandunnington approved these changes

2022-11-03 16:52 UTC, gewarren commented
#sign-off

2022-11-03 19:00 UTC, Rick-Anderson commented
#sign-off

2022-11-03 19:30 UTC, gewarren commented
@bharney0 Can you merge this?

2022-11-03 19:31 UTC, merged